# simple catalog 
catalog: 
  name: Catalog
  short: a simple catalog
  description: this is a catalog
  datatype: catalog
  versions: [v1.0, v2.0, v3.0]
  example: simplework/catalogs/catalogA_v3.0.csv
  stuff: A 
