# simple catalog 
catalog: 
  name: Catalog
  short: a simple catalog
  description: this is a catalog
  datatype: catalog
  example: simple/catalogs/catalogA_v3.0.csv
  versions: [v1.0, v2.0, v3.0, v4.0]
  stuff: A 
  